[tool.poetry]
name = "pewwe"
version = "0.1.0"
description = ""
authors = ["Bruno Fioreze"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
peewee = "^3.16.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
